Added 1440p resolution option
moonlight-stream/moonlight-ios pull request #521
Opened 2022-08-16 03:16 UTC by Starlank

Was originally done by [pierguil](https://github.com/pierguil), but it looks like their branch is outdated.

2022-08-17 04:52 UTC, cgutman commented
Let's limit this to tvOS (which lacks custom resolution support) only

iOS can use the custom resolution option to use 1440p already. Due to GeForce Experience behaving badly with resolutions that aren't 720p, 1080p, or 4K, I'd like users to go through the UX flow that displays the custom resolution warning dialog on iOS.

2022-08-17 04:55 UTC, cgutman requested changes

2022-08-17 04:55 UTC, cgutman commented on Limelight/Database/TemporarySettings.m
> +        case 3:
It's not safe to use 2 for 1440p, because 2 is what is currently used for 4K. You should use 3 for 1440p instead.

2022-08-18 01:47 UTC, Starlank commented
Does this look better? Isolated it to just tvOS, and changed 1440p to option 3.

2022-08-18 03:37 UTC, cgutman approved these changes
Perfect, thanks.

2022-08-18 03:38 UTC, merged