Added OSC Layout and Visibility Configurability, #495, #450, #392, and #389
moonlight-stream/moonlight-ios pull request #546
Opened 2023-01-15 22:58 UTC by King0fSpace

This commit implements a feature discussed in #495 , #450 , #392 , and #389 . 

It allows users to hide and move any of the on screen controller buttons anywhere they’d like on screen. The user can save their custom layouts under user-defined names. Multiple controller ‘profiles’ can be saved. Profiles can be loaded from a menu that lists all of the user’s saved profiles. The user can swipe-to-delete any user-saved profiles they'd like from this screen as well.

This feature has been made accessible in an unobtrusive way; by tapping the ‘Custom’ button added to the end of the existing ‘On-Screen Controls’ buttons bar, located within the existing ‘Settings’ slide out menu. 

![IMG_4465](https://user-images.githubusercontent.com/67873955/212571578-0ef7c217-1bcc-4522-a761-d063482c061b.jpeg)
![IMG_4466](https://user-images.githubusercontent.com/67873955/212571466-d4e27081-abcf-41ef-91c7-31d9247eeb4f.jpeg)
7c93.jpeg)
![IMG_4464](https://user-images.githubusercontent.com/67873955/212571470-7dd485d7-3c84-435f-867b-c1eaa8b3c294.jpeg)
![IMG_4463](https://user-images.githubusercontent.com/67873955/212571478-640895b6-24ab-424c-a41a-0032109591c2.jpeg)
![IMG_4490](https://user-images.githubusercontent.com/67873955/212571480-4e8a0ab5-8450-4a4a-9e75-8269356c2882.jpeg)
![IMG_4470](https://user-images.githubusercontent.com/67873955/212571481-a5b29cc0-136c-440e-8ef9-cc0804ad8392.jpeg)
![IMG_4472](https://user-images.githubusercontent.com/67873955/212571482-3874505c-d0fa-4f1c-8949-bd218f853edd.jpeg)

iPad
![IMG_0047](https://user-images.githubusercontent.com/67873955/212571500-f0183f0a-c104-4c7d-8411-2f5d3fd39c02.jpeg)

2023-03-14 03:22 UTC, cgutman commented
Sorry for the delays reviewing this. I've been trying to get fixes out for various Moonlight clients.

I will try to take a look by this weekend.

2023-03-14 05:10 UTC, King0fSpace commented
No worries. I love the app. Thanks very much

2023-03-21 05:09 UTC, cgutman requested changes
It looks like there are a bunch of extraneous files moved/deleted/added that aren't related to the change here (ex: `.DS_Store`, all of `moonlight-common-c`, `pbxproj` files, etc).

Can you rebase your branch to only include the relevant changes for your feature?

2023-03-21 05:09 UTC, cgutman commented on .gitmodules.save
> +	url = https://github.com/moonlight-stream/moonlight-common-c
Looks like this file was committed accidentally

2023-03-21 05:09 UTC, cgutman commented on .gitmodules
> +	url = https://github.com/cgutman/X1Kit.git
Can you revert these? They don't seem relevant to the PR here.

2023-03-21 05:09 UTC, cgutman commented on .gitignore
> -DerivedData
Please revert this removal

2023-03-21 05:09 UTC, cgutman commented on .DS_Store
Please remove these `.DS_Store` files

2023-06-27 21:29 UTC, closed without merging

2023-06-27 21:29 UTC, King0fSpace commented
Opened another pull request